### PR TITLE
Remove Test from beta and v1 known issues.

### LINKED ISSUE #553: Site: GetApplicableContentTypesForList Requires ListId
https://docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-1.0&tabs=csharp

The snippet below requires `listId` to be set with a value from our Identitifers.
Possible Solutions:-
- Add ListId to Edge Cases and Replace it with a correct ID from our Identifiers. 
- Fix Snippet Generator to make `listId` become `{list-id}` for it to be handled by IdReplacer. 

If https://github.com/microsoftgraph/microsoft-graph-docs/pull/14824 is merged this issue will be auto-resolved. 
```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var getApplicableContentTypesForList = await graphClient.Sites["{site-id}"]
	.GetApplicableContentTypesForList("listId")
	.Request()
	.GetAsync();
```
cc. @andrueastman

### PR DESCRIPTION
**Pull request by georgend**
Add edge case till docs can be corrected as detailed in referenced issue. 
Remove Tests from known issues. 

***Minor Changes***
Make TestResults, Test Run Settings Solution Items for easier navigation. 

Closes #553

### CODE REVIEW

**Review by zengin — CHANGES_REQUESTED** [review]
I don't think we should hide documentation issues with workarounds. Please create an issue in docs and link that as the root cause and update the list here: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/503

**Comment by georgend** [comment]
I have linked the issue. 
The change has been merged into the docs: https://github.com/microsoftgraph/microsoft-graph-docs/pull/14798.
I will remove the edge case. 
Awaiting Snippet Generation.

**Review by zengin — APPROVED** [review]
approving, but please merge after confirming that the corresponding test passes after the docs have the snippet changes.

**Comment by zengin** [comment]
snippets seem to have merged, merged dev and pushed to kick off CI.

**Pull request merged**
