### PR TITLE
Json Parsing Exception in IDTree when _value is a Number

### PR DESCRIPTION
**Pull request by georgend**
IDTree values can be integers or floating points numbers, assumption that all _value are strings no longer holds and would require `.ToString()` in PowerShell data generation scripts. 
Add tests to verify new IDTree behavior.

### CODE REVIEW

**Comment by zengin** [comment]
Why don't we keep everything as string though, given that the values we are replacing are always strings?

Maybe we should fix this in the generation scripts e.g. while assigning, _value = "$id_value_from_query" to force assign a string value.

**Review by fey101 — APPROVED** [review]
LGTM. Thanks for this fix

**Comment by fey101** [comment]
> Why don't we keep everything as string though, given that the values we are replacing are always strings?
> 
> Maybe we should fix this in the generation scripts e.g. while assigning, `_value = "$id_value_from_query"` to force assign a string value.

@zengin , isn't that option restraining? The logic remains in our head and it's subject to not being adhered to if someone else without this knowledge works on the scripts. Why not have the same logic in code instead?

**Comment by fey101** [comment]
Looks like the auto-merge was on and I had not read @zengin  comment before approving. My apologies.

**Comment by georgend** [comment]
Letme undo the PR, till we address the other points.

**Pull request merged**
