### PR TITLE
Add code owners

### PR DESCRIPTION
**Pull request by zengin**

### CODE REVIEW

**Review by MIchaelMainer — APPROVED** [review]

**Comment by baywet** [comment]
@zengin did you have an opportunity to test it? I didn't have time to test it on Java service and couldn't figure out if the branching policies must be configured to use this for or if it's optional.

**Comment by zengin** [comment]
worked here: https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/129

**Comment by baywet** [comment]
Right, because the dependabot configuration only has both of us https://www.github.com/microsoftgraph/msgraph-sdk-raptor/tree/dev/.github%2Fdependabot.yml

**Comment by zengin** [comment]
oh, I should have updated that file too.

**Pull request merged**
