### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by MIchaelMainer**

### CODE REVIEW

**Review by zengin — APPROVED** [review]

**Comment by nikithauc** [comment]
What is the reason for this  change?

**Review by nikithauc — APPROVED** [review]

**Comment by zengin** [comment]
merging to unblock pipeline queues.

**Comment by MIchaelMainer** [comment]
@nikithauc Microsoft Graph is a product/service/brand and is not the legal holder of the copyright.

**Comment by nikithauc** [comment]
> @nikithauc Microsoft Graph is a product/service/brand and is not the legal holder of the copyright. 

Thanks for the information!

**Pull request merged**
